branch-defaults:
  default:
    environment: eb-django-skeleton-env
    group_suffix: null
environment-defaults:
  eb-django-skeleton-env:
    branch: null
    repository: null
global:
  application_name: eb-django-skeleton
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.6
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
